---
title: "MusicDatabase"
author: Collin Smith, Conor Burrows, Jake Luedtke, Nicholas Melon
date: "January 25, 2017"
output: html_document
---


## First Steps

```{r}
library(stringr)
#Get dataset and look at name and title
allsongs <- read.csv("tsort-chart-2-6-0013.csv")
nsongs <- allsongs[,1:2]
#Set as characters
nnsongs <- as.character(nsongs$name)
#Make sure song names are in correct format
lsongs <- tolower(nnsongs)
lsong <- str_extract_all(lsongs, boundary("word"))

#test <- head(lsong, n = 20)
#Empty list for words
words <- list()
#Function looks at song titles, splits them up into words, adds them to a list and keeps track of number 
dtf <- data.frame()
for (x in 1:length(lsong)){
  title <- lsong[[x]]
  for (y in 1:length(title)){
    word <- title[[y]]
    if(exists(word, words)){
      words[[word]] <- words[[word]] + 1
    }else{
      words[[word]] <- 1
    }
    
  }
}

saveRDS(words, "words.txt")
#Formatting Data
mdf <- as.data.frame(words)
gmdf <- t(mdf)
nad <- c("Instances")
colnames(gmdf) <- nad
#Function to 
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
